### ISSUE TITLE
"Music Tech & Innovation" subcategory of main menu "Data" doesn't work

### ISSUE THREAD

**Issue by BoriD** [dataobservatory-eu/music#10]
On DMO website, the main menu point "Data" contains 6 subcategories, as follows: "Music & Economy", "Diversity and Circulation", "Music & Society", "Music Tech & Innovation", "Open sciene repository" "API".

"Music Tech & Innovation" subcategory doesn't work.

**Comment by antaldaniel** [comment]
@BoriD Please review the solution and the changes in the README of this [repo](https://github.com/dataobservatory-eu/music), and if it works, close the issue.
